# bundle exec jekyll serve --livereload
#page title
page_title                                : #(상단탭 이름)  

# App Info_text
ios_app_id                                : 1509623459                   # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/kr/app/%EB%AF%B8%EC%84%B8%EC%98%81/id1509623459    # (앱스토어 url)
appstore_berry_link                       :
appstore_misezero_link                    :

playstore_link                            :                                           # Enter Google Play Store URL.
playstore_berry_link                      :
playstore_misezero_link                   :
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
#your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           #(앱아이콘 이미지)

app_name                                  :                                        #(앱아이콘 옆의 앱이름)
app_berry_name                            : BERRY
app_misezero_name                         : Misezero

app_price                                 :                                           #(앱이름 하단)
app_berry_price                           : Free
app_misezero_price                        : Free

app_description                           :                                         #(앱 설명)
app_berry_description                     : period tracking     
app_misezero_description                  : Finedust information in Korea     

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Site Settings 
title                                     : title test 
url                                       : https://penguinmilk.github.io/            # URL

# Information About Yourself
your_name                                 :                              
your_link                                 :                      
your_city                                 :                               
email_address                             :
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          :
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : useful app
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : thumbs-up # magic
    
  - title                                 : easy app
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile

  - title                                 : beautiful app
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : mobile-alt
    
# misezoro feature list
misezero-features                         :

  - title                                 : checking air quality
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : wind #adjust
  
  - title                                 : checking weather
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : sun #star

  - title                                 : Checking anytime & anywhere
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : map-pin #arrow-alt-circle-down
    
# berry feature lest
berry-features                            :

  - title                                 : Period Tracking
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : calendar-check #link

  - title                                 : Data visualizing
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : chart-bar #info-circle

  - title                                 : Easy handling
    description                           : New Feature Description
    fontawesome_icon_name                 : grin-hearts                      # Find free icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown